plugins {
    id 'com.android.application'
}

android {
    namespace 'de.roman.samsungirremote'
    compileSdk 36

    defaultConfig {
        applicationId 'de.mason.samsungtvircontroller'
        minSdk 23
        targetSdk 36
        versionCode 3
        versionName '1.1.1-android16'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
